# Generated by Django 2.2.3 on 2019-11-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngomember',
            name='ngo_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userlog.Ngo'),
        ),
    ]
