# Generated by Django 2.2.3 on 2019-11-13 08:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=None, max_length=50)),
                ('full_name', models.CharField(default=None, max_length=50)),
                ('child_id', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='image/child')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=6)),
                ('age', models.IntegerField(default=None)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('message', models.TextField(default=None, max_length=400)),
                ('submit_on', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(default='abcd123@gmail.com', max_length=254)),
                ('subject', models.CharField(default=None, max_length=50)),
                ('message', models.TextField(default=None, max_length=400)),
                ('submit_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileData',
            fields=[
                ('username', models.CharField(default='user', max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('profile_pic', models.ImageField(blank=True, upload_to='image/users')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=6)),
                ('age', models.IntegerField(default=None)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None)),
                ('is_volunteer', models.BooleanField(default=False)),
                ('is_ngo_member', models.BooleanField(default=False)),
                ('accept', models.BooleanField(default=False)),
            ],
        ),
    ]
